### ISSUE TITLE
When executing terragrunt plan, the below error is output.

### ISSUE THREAD

**Issue by fn-jbarker** [BorisLabs/terraform-aws-directconnect#11]
`Error: Invalid index

  on outputs.tf line 2, in output "dx_connection_id":
   2:   value = aws_dx_connection.this[0].id
    |----------------
    | aws_dx_connection.this is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on outputs.tf line 6, in output "dx_connection_bandwidth":
   6:   value = aws_dx_connection.this[0].bandwidth
    |----------------
    | aws_dx_connection.this is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on outputs.tf line 10, in output "dx_connection_arn":
  10:   value = aws_dx_connection.this[0].arn
    |----------------
    | aws_dx_connection.this is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on outputs.tf line 14, in output "dx_connection_name":
  14:   value = aws_dx_connection.this[0].name
    |----------------
    | aws_dx_connection.this is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on outputs.tf line 18, in output "dx_private_hosted_vif_id":
  18:   value = aws_dx_hosted_private_virtual_interface.private_vif[0].id
    |----------------
    | aws_dx_hosted_private_virtual_interface.private_vif is empty tuple

The given key does not identify an element in this collection value.

Error: Invalid index

  on outputs.tf line 22, in output "dx_private_hosted_vif_arn":
  22:   value = aws_dx_hosted_private_virtual_interface.private_vif[0].arn
    |----------------
    | aws_dx_hosted_private_virtual_interface.private_vif is empty tuple

The given key does not identify an element in this collection value.

ERRO[0005] 1 error occurred:
        * exit status 1`

**Comment by JoshiiSinfield** [comment]
Hi @fn-jbarker , apologies for a late reply this one slipped past us.

Have you reproduced using the latest version? These output values have changed a while ago...

Cheers,
Josh

**Comment by fn-jbarker** [comment]
Thank you for getting back to me Josh.  I no longer have a need thankfully,
we decommissioned our data center.

Regards,
Jim Barker
